### ISSUE TITLE
Timeline drawn for PDF

### ISSUE THREAD

**Issue by eileenvanheerde** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#100]
**Describe the bug**
Timeline is still drawn when a PDF file is selected to upload.

**To Reproduce**
1. Go to https://dev.braunson.me/
2. Click on 'Browse'
3. Select a PDF file
4. Click 'OK' for both alerts
5. Timeline should be drawn

**Expected behavior**
I expect no timeline to be drawn after both alerts are closed.

**Screenshots**
![image](https://user-images.githubusercontent.com/47048148/68175125-cf76b380-ff45-11e9-8ee3-6c08e8342b02.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by braunsonm** [comment]
@ank266 Does your current PR solve this?

**Comment by camilleion** [comment]
Fixed by Anarag
