### ISSUE TITLE
Add pre/post conditions from design docs to codebase

### ISSUE THREAD

**Issue by ets994** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#108]
**Add Pre/Post conds**
The pre/post conditions were added to the design documents in ID3.  These should be added by the dev team to make sure they inline with what's actually happening in the the program.  Anyone from the dev team could do this or it could be done together, this should also help us build some assertions in to the software.

**Comment by camilleion** [comment]
@braunsonm not sure if number of closed issues is tracked but did you want to close this one?

**Comment by braunsonm** [comment]
It will automatically be closed when my PR is merged @camilleion
