### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by braunsonm** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#11]
We should have an agreed upon code style documented in the repository.

**Comment by braunsonm** [comment]
@ets994 How about we use the ES6 coding style?

The rules are documented here: https://standardjs.com/rules.html

**Comment by camilleion** [comment]
My 370 group used the google coding convention and it was pretty good! Obviously open to others.

for a brief overview:
https://www.infoq.com/news/2014/02/google-java-coding-standards/

for the full documentation:
https://google.github.io/styleguide/javaguide.html

**Comment by braunsonm** [comment]
Hmm @camilleion do you know if Google has Javascript coding conventions? The linked ones are for Java. :(

**Comment by camilleion** [comment]
Oops sorry! Yes they do, although I have not used it and now no longer have a foot in the game.
brief overview:
https://www.freecodecamp.org/news/google-publishes-a-javascript-style-guide-here-are-some-key-lessons-1810b8ad050b/

full documentation:
https://google.github.io/styleguide/javascriptguide.xml

**Comment by ets994** [comment]
Yeah, sorry for the late response on this.  I thought we had landed on something specific and I believe most team members are currently under the usage of the google style guide.  I'm going to leave this up for 1 more day and if I hear no objections it's finalized.

**Comment by ets994** [comment]
Closed as per [this](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2/commit/d7860f0c78cc577920c09b9219b6a1be451c871b) meeting.
