### ISSUE TITLE
'Data is EMPTY' alert shown when file has data

### ISSUE THREAD

**Issue by eileenvanheerde** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#126]
**Describe the bug**
When uploading a csv file with valid data, an alert pops up saying that the "data is EMPTY". This only occurs when using FireFox but is not an issue on Chrome. The date also does not get parsed correctly when using FireFox.

**To Reproduce**
1. Go [here](https://dev.braunson.me/) using Firefox
2. Click on _browse_
3. Select a valid csv that isn't '10000 sales records.csv'.
4. Alert should pop up saying "data is EMPTY"
5. Click 'OK'
6. Should still draw a timeline

**Expected behavior**
No alert should pop up.

**Screenshots**
Alert popping up.
![image](https://user-images.githubusercontent.com/47048148/69014010-aa257480-094b-11ea-9827-770ed6e11064.png)

ParserComponent state is updated to contain data after clicking 'OK'
![image](https://user-images.githubusercontent.com/47048148/69014068-11dbbf80-094c-11ea-87bb-aa17f8ff3548.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox 70.0.1 (64-bit)

**Comment by camilleion** [comment]
Not an issue for current build
