### ISSUE TITLE
Zoom should be able to zoom out further than base scale

### ISSUE THREAD

**Issue by braunsonm** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#150]
**Describe the bug**
You should have the ability to zoom out further than the base scale 1. Right now the initial zoom is locked in as the most zoomed out.

**To Reproduce**
1. Open up a CSV
2. Try to zoom out

**Expected behavior**
You should be able to zoom out further

**⏰ Estimated Time**
1 hour

**Comment by camilleion** [comment]
Completed
