### ISSUE TITLE
Zoom on interval occurrence timeline does not work

### ISSUE THREAD

**Issue by braunsonm** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#153]
**Describe the bug**
Zooming on the interval occurrence view does not seem to work at all.

**To Reproduce**
1. Upload a CSV
2. Try to zoom and notice nothing happens

**Expected behavior**
Zooming should behave normally

**⏰ Estimated Time**
30 mins

**Comment by camilleion** [comment]
I'm not sure I 'fixed' it but I disabled the functionality of zooming on interval occurrence b/c the x-axis zoomed only so it was broken. Not it does not exist.

**Comment by camilleion** [comment]
Jk now fixed as per Mesa's PR
