### ISSUE TITLE
Requirements document

### ISSUE THREAD

**Issue by braunsonm** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#16]
The requirements document must be completed. This issue will be updated with tasks when discussed.

**Comment by braunsonm** [comment]
I believe @cessien66 and @mkoma808 were assigned to this? Please edit the above issue and add some github [tasks](https://help.github.com/en/articles/about-task-lists)

**Comment by cessien66** [comment]
Definitely. I will talk to Mesa and we will go from there
