### ISSUE TITLE
Panning forever

### ISSUE THREAD

**Issue by braunsonm** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#164]
**Describe the bug**
Holding down one of the buttons and then opening a dropdown, the app will never see the keyup event and conintue like those keys are being still held down.

**To Reproduce**
1. Upload a CSV
2. Start panning and open a dropbox
3. You'll notice it keeps panning forever

**Expected behavior**
The panning should stop when the key is removed or when a dropdown is pressed

**⏰ Estimated Time**
30 mins

**Comment by camilleion** [comment]
Duplicate of Amanda's error
