### ISSUE TITLE
Dragging on points can cause multiple popups to display

### ISSUE THREAD

**Issue by braunsonm** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#170]
**Describe the bug**
Clicking and dragging to pan on a point that displays information about the data, can cause multiple popup views to show data.

**To Reproduce**
1. Upload a CSV
2. Drag to pan on a point that causes a popup
3. Notice that sometimes multiple pop up's are displayed with information at one time

**Expected behavior**
Only one popup should be displayed at a time, preferable hide all popups when panning

**⏰ Estimated Time**
30 mins

**Comment by camilleion** [comment]
Can still happen but is much more difficult to reproduce.
