### ISSUE TITLE
Odd behavior when handling a summary point

### ISSUE THREAD

**Issue by aaz713** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#176]
When hovering over, clicking, and dragging a data point, it's difficult to exit the summary, and when panning along the timeline, the data summary follows

1. Launch React App
2. Select any data point with your mouse and attempt to drag it along the screen
3. Try to exit the summay (Error)
4. Attempt to pan along timeline via click-and-drag or arrow keys

 - OS: Windows 10
 - Browser: Chrome

⏰ Estimated Time: ??

**Comment by ets994** [comment]
Is this the same as #170 ?

**Comment by camilleion** [comment]
Fixed as per Mesa's PR
