### ISSUE TITLE
X axis labels aren't scaled properly

### ISSUE THREAD

**Issue by ets994** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#183]
**X axis labels are bad**
The X axis labels aren't scaled or drawn properly

**To Reproduce**
1. Upload a csv with several of the same value repeated and one large value at the end (example 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 100)
2. the label on the X axis doesn't accurately represent the range of data

**Expected behavior**
The X axis should be scaled by the data, not just tacked on to the values values it happens to be rendering underneath

**⏰ Estimated Time**
~30-60 minutes

**Comment by camilleion** [comment]
Fixed as per Mesa's PR
