### ISSUE TITLE
Structured readme for ID1

### ISSUE THREAD

**Issue by ets994** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#19]
We need a readme that explains all of the various places where
the different parts of ID1 live (google docs, on the repo, etc etc)

**Comment by braunsonm** [comment]
Note that roles are in the policy document here: https://github.com/UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2/blob/master/documents/policy/policy.pdf
