### ISSUE TITLE
Weird zoom in behaviour during event occurence

### ISSUE THREAD

**Issue by aaz713** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#192]
When switching the timeline type to event occurrence and attempting to zoom in, the location of the points remain unchanging

1. Launch React with Google Chrome
2. Upload .csv
3. Change timeline type to "event occurrence"
4. Zoom in with mousewheel
5. See error

![bug](https://user-images.githubusercontent.com/55122110/70191120-635eab00-16bd-11ea-8171-29d23450432d.png)

**Comment by camilleion** [comment]
This issue already exists
