### ISSUE TITLE
Stubs Need to be Written

### ISSUE THREAD

**Issue by ets994** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#38]
Function stubs and headers for classes need to be written so we can paralellize test writing, documentation writing, and iron out any kinks in the build pipeline before we go into a regular build schedule.

**Comment by mkoma808** [comment]
Stubs and headers for classes are complete and on the develop branch.

Some of the inputs and outputs were changed from the design doc to better reflect code flow and best practices.

Will update the design doc ASAP.

**Comment by ets994** [comment]
Nice, hopefully this will get us on track for some parallel development
