### ISSUE TITLE
Expand The Formal Review Documents

### ISSUE THREAD

**Issue by ets994** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#41]
**Formal Review Docs**
As per [this](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2/commit/d7860f0c78cc577920c09b9219b6a1be451c871b) meeting, we need to improve our formal process.  The document should outline a few extra things:
 - What roles people take in the meeting
 - What was prepared before the meeting
 - What was discussed during the meeting
 - Outline of the issues document, or perhaps a format for an issues document

**Comment by camilleion** [comment]
I don't think we have to document what was prepared before the meeting, I think each reviewer comes in with a pre-prepared list from what I understood in class. Also I believe the role of 'recorder' was to note all things discussed during the meeting but I believe he said for us this was an optional role.

**Comment by braunsonm** [comment]
@camilleion I remember you having a PR that updated this. Is this complete?

**Comment by camilleion** [comment]
Yes, sorry I forgot to close this issue!
