### ISSUE TITLE
Spike Prototypes Central Document

### ISSUE THREAD

**Issue by ets994** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#42]
**Central Readme for Prototypes**
We need a centralized document for any spike prototypes that have been created. I've added everyone to this issue who worked on any prototypes so far.

**Comment by braunsonm** [comment]
Closed in: https://github.com/UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2/commit/0321b0e5e00fe926a52a170c5dc62b2f9f4bb0cd
