### ISSUE TITLE
Latest meeting files have unknown characters

### ISSUE THREAD

**Issue by braunsonm** [UniversityOfSaskatchewanCMPT371/term-project-fall2019-team-2#8]
They seem to use different types of bullets and some text editors can’t recognize them.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/5280764/65731738-299d7280-e084-11e9-8029-f9f7a2d055f9.png">

**Comment by braunsonm** [comment]
Is this fixed in fe4a2347d3ad08ea153c3f4d81be7d1801efc92d? @aaz713

**Comment by ets994** [comment]
This was fixed it appears so I'm closing it to keep issues clean.
